name: pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=19.3.1
  - python=3.7.4
  - pytorch=1.3.0
  - torchvision=0.4.1
  - pip:
    - pytorch-lightning==0.5.2.1
    - matplotlib==5.2.2
